import os
import shutil
import stat
import subprocess
import logging
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from configobj import ConfigObjError

from ..common.checks import NameChecker
from ..lmnfile import LMNFile
from .drivers import (
    DriverProfileAssignedError,
    IMAGE_CONF_FILENAME,
    LinboDriverManager,
    _mutation_lock,
)
from .models import ImageInfo


logger = logging.getLogger(__name__)

LINBO_PATH = '/srv/linbo/images'
TIMESTAMP_FMT = '%Y%m%d%H%M'
DATE_UI_FMT = '%d/%m/%Y %H:%M'


# Filenames like ubuntu.qcow2.desc
EXTRA_IMAGE_FILES = ['desc', 'info', 'vdi']
EXTRA_NONEDITABLE_IMAGE_FILES = ['torrent', 'macct', 'md5']

# Filenames like ubuntu.reg
EXTRA_COMMON_FILES = ['reg', 'postsync', 'prestart']

ALL_FILES_EXT = EXTRA_IMAGE_FILES + EXTRA_NONEDITABLE_IMAGE_FILES + EXTRA_COMMON_FILES

EXTRA_PERMISSIONS_MAPPING = {
    'desc': 0o664,
    'info': 0o664,
    'macct': 0o600,
    'vdi': 0o664,
    'reg': 0o664,
    'postsync': 0o664,
    'prestart': 0o664,
}
IMAGE = "qcow2"
DIFF_IMAGE = "qdiff"

DRIVERPOSTSYNC_MANAGED_HEADER = (
    "# Managed-By: linuxmusterTools.linbo.images driverpostsync v1"
)
DRIVERPOSTSYNC_LEGACY_HEADERS = frozenset(
    {
        "# Managed-By: linuxmusterTools.linbo.driver_hooks v1",
        "# Generated by LINBO Patchless — DO NOT EDIT MANUALLY",
    }
)
DRIVERPOSTSYNC_OWNERSHIP_HEADERS = frozenset(
    {DRIVERPOSTSYNC_MANAGED_HEADER, *DRIVERPOSTSYNC_LEGACY_HEADERS}
)
DRIVERPOSTSYNC_SUFFIX = ".driverpostsync"

name_checker = NameChecker()


class DriverPostsyncOwnershipError(RuntimeError):
    """Raised when an existing driver hook is not owned by this manager."""


def _ignore_duplicate_files(_directory, names):
    """Do not clone backups or per-image driver dispatchers."""

    return [
        name
        for name in names
        if name in {"backup", "backups"} or name.endswith(DRIVERPOSTSYNC_SUFFIX)
    ]

def date2timestamp(date):
    return datetime.strptime(date, DATE_UI_FMT).strftime(TIMESTAMP_FMT)

def timestamp2date(timestamp):
    return datetime.strptime(timestamp, TIMESTAMP_FMT).strftime(DATE_UI_FMT)

class LinboImage:
    """
    A class to manage a linbo image or a backup image
    """

    def __init__(self, name, backup=False, timestamp=None, diff=False):
        self.name = name
        self.backup = backup
        self.diff = diff
        self.timestamp = timestamp
        self.load_info()

    def _torrent_stop(self):
        try:
            subprocess.check_output(['/usr/sbin/linbo-torrent', 'stop', os.path.join(self.path, f'{self.image}.torrent')])
        except Exception as e:
            logger.error(f'Unable to stop torrent service for {self.image} : {e.output}')

    def load_info(self):
        """
        Prepare all variables to manage the image object ( path, name, extra files )
        """

        if self.diff:
            self.image = f"{self.name}.{DIFF_IMAGE}"
        else:
            self.image = f"{self.name}.{IMAGE}"

        if self.backup:
            self.path = os.path.join(LINBO_PATH, self.name, 'backups', self.timestamp)
            self.date = timestamp2date(self.timestamp)
        else:
            self.path = os.path.join(LINBO_PATH, self.name)
            self.parse_info_file()
            self.timestamp = self.info_file.timestamp
            self.date = timestamp2date(self.timestamp)

        self.size = os.stat(os.path.join(self.path, self.image)).st_size
        self.extras = {} # TODO rename to raw extras
        self.get_extra()

    def get_extra(self):
        """
        Load raw content of extra editables config files.
        """

        for extra in EXTRA_IMAGE_FILES:
            extra_file = os.path.join(self.path, f"{self.image}.{extra}")
            if os.path.isfile(extra_file):
                with LMNFile(extra_file, 'r') as f:
                    self.extras[extra] = f.read()
            else:
                self.extras[extra] = None
                # Create empty desc in any case
                if extra == 'desc' and os.getuid() == 0:
                    with LMNFile(extra_file, 'w') as f:
                        pass
                    os.chmod(extra_file, EXTRA_PERMISSIONS_MAPPING[extra])

        for extra in EXTRA_COMMON_FILES:
            if self.diff and extra == 'postsync':
                continue
            extra_file = os.path.join(self.path, f"{self.name}.{extra}")
            if os.path.isfile(extra_file):
                with LMNFile(extra_file, 'r') as f:
                    self.extras[extra] = f.read()
            else:
                self.extras[extra] = None

    def parse_info_file(self):
        info_path = os.path.join(self.path, f"{self.image}.info")
        attributes = {}
        if os.path.isfile(info_path):
            with open(info_path, 'r') as info:
                for line in info:
                    if '=' in line:
                        # Support timestamp=2021..
                        # and timestamp="2021..."
                        k, v = line.strip().split('=')
                        v = v.strip('"')
                        attributes[k] = v
        self.info_file = ImageInfo(**attributes)

    def delete_files(self):
        """
        Delete all files from a LinboImage.
        """

        # Remove image
        image_path = os.path.join(self.path, self.image)
        if os.path.exists(image_path):
            os.unlink(os.path.join(self.path, self.image))

        # Remove extra files
        for extra in EXTRA_IMAGE_FILES + EXTRA_NONEDITABLE_IMAGE_FILES:
            path = os.path.join(self.path, f"{self.image}.{extra}")
            if os.path.exists(path):
                os.unlink(path)

        for extra in EXTRA_COMMON_FILES:
            if self.diff and extra == 'postsync':
                continue
            path = os.path.join(self.path, f"{self.name}.{extra}")
            if os.path.exists(path):
                os.unlink(path)

    def delete(self):
        """
        Completely remove an image and its directory.
        """

        if not self.backup:
            self._torrent_stop()

        self.delete_files()

        if not self.diff:
            # Remove directory
            try:
                os.rmdir(self.path)
            except OSError as e:
                # TODO: better handle this
                print(e)
                #raise EndpointError(e)

    def rename(self, new_name):
        """
        Rename a LinboImage and all its files.
        """

        if self.diff:
            new_image_name = f"{new_name}.{DIFF_IMAGE}"
        else:
            new_image_name = f"{new_name}.{IMAGE}"

        if not self.backup:
            self._torrent_stop()

        # Rename image
        os.rename(os.path.join(self.path, self.image),
                  os.path.join(self.path, new_image_name))

        # Rename extra files
        for extra in EXTRA_IMAGE_FILES + EXTRA_NONEDITABLE_IMAGE_FILES:
            actual = os.path.join(self.path, f"{self.image}.{extra}")
            if os.path.exists(actual):
                # Replace image name in .info file
                if extra == "info":
                    with LMNFile(actual, 'r') as info:
                        data = info.read().replace(self.image, new_image_name)
                    with LMNFile(actual, 'w') as info:
                        info.write(data)

                # Need to generate a new torrent file
                if extra == "torrent":
                    os.unlink(actual)

                    continue

                os.rename(actual, os.path.join(self.path, f"{new_image_name}.{extra}"))

        for extra in EXTRA_COMMON_FILES:
            actual = os.path.join(self.path, f"{self.name}.{extra}")
            if os.path.exists(actual):
                os.rename(actual, os.path.join(self.path, f"{new_name}.{extra}"))

        # Move directory
        if not self.backup and not self.diff:
            os.rename(self.path, os.path.join(LINBO_PATH, new_name))

        # Refresh informations
        self.name = new_name

    def save_extras(self, data):
        """
        Save all extra files content.

        :param data: Data to save
        :type data: dict
        """

        for extra in EXTRA_IMAGE_FILES:
            path = os.path.join(self.path, f"{self.image}.{extra}")
            extra_content = data.get(extra, '')
            if extra_content or (extra == "desc" and extra_content is not None):
                with LMNFile(path, 'w') as f:
                    f.write(data[extra])
                os.chmod(path, EXTRA_PERMISSIONS_MAPPING[extra])
            else:
                if os.path.exists(path):
                    os.unlink(path)

        for extra in EXTRA_COMMON_FILES:
            path = os.path.join(self.path, f"{self.name}.{extra}")
            extra_content = data.get(extra, '')
            if extra_content:
                with LMNFile(path, 'w') as f:
                    f.write(data[extra])
                os.chmod(path, EXTRA_PERMISSIONS_MAPPING[extra])
            else:
                if os.path.exists(path):
                    os.unlink(path)

    def to_dict(self):
        """
        Convert all necessary infos into a dict for angular.
        """

        return {
            'name': self.name,
            'size': self.size,
            'desc': self.extras['desc'],
            'info': self.extras['info'],
            'reg': self.extras['reg'],
            'postsync': self.extras.get('postsync', ''),
            'vdi': self.extras['vdi'],
            'prestart': self.extras['prestart'],
            'backup': self.backup,
            'diff': self.diff,
            'timestamp': self.timestamp,
            'date': self.date,
        }

class LinboImageGroup:
    """
    Class to handle a basic LinboImage and all his backups.
    """

    def __init__(self, name):
        self.name = name
        self.path = os.path.join(LINBO_PATH, self.name)
        self.backup_path = os.path.join(LINBO_PATH, self.name, 'backups')
        self.load()

    def load(self):
        self.backups = {}
        self.base = LinboImage(self.name)
        self.get_backups()
        self.get_diff()

    def get_backups(self):
        """
        Browse current tree to find all backups image.
        """

        if os.path.exists(self.backup_path):
            for timestamp in os.listdir(self.backup_path):
                try:
                    # Is it a valid timestamp ?
                    timestamp2date(timestamp)
                except ValueError:
                    # Not a backup done with Linbo, passing
                    continue
                for file in os.listdir(os.path.join(self.backup_path, timestamp)):
                    if file.endswith(f".{IMAGE}"):
                        self.backups[timestamp2date(timestamp)] = LinboImage(
                            self.name,
                            backup=True,
                            timestamp=timestamp
                        )

    def get_diff(self):
        """
        Browse current tree to find a differential image.
        """

        if os.path.exists(os.path.join(LINBO_PATH, self.name, f'{self.name}.{DIFF_IMAGE}')):
            self.diff_image = LinboImage(self.name, diff=True)
        else:
            self.diff_image = None

    def rename(self, new_name):
        """
        Rename an image and all his backups.
        """

        for timestamp, backup in self.backups.items():
            backup.rename(new_name)

        if self.diff_image:
            self.diff_image.rename(new_name)

        self.base.rename(new_name)

        # Refresh informations
        self.base.load_info()

        for timestamp, backup in self.backups.items():
            backup.load_info()

        self.name = new_name
        self.path = os.path.join(LINBO_PATH, self.name)
        self.backup_path = os.path.join(LINBO_PATH, self.name, 'backups')

    def delete(self):
        """
        Delete basic image, all backups, diff image and all config files.
        """

        for timestamp, backup in self.backups.items():
            backup.delete()

        if self.diff_image:
            self.diff_image.delete()

        if os.path.isdir(self.backup_path):
            try:
                os.rmdir(self.backup_path)
            except OSError as e:
                # TODO: better handle this
                print(e)
                #raise EndpointError(e)

        self.base.delete()

    def to_dict(self):
        result = self.base.to_dict()
        result['diff_image'] = self.diff_image.to_dict() if self.diff_image else {}
        result['backups'] = {
            timestamp: backup.to_dict()
            for timestamp, backup in self.backups.items()
        }
        result['selected'] = False
        return result

class LinboImageManager:
    """
    Manager for all Linbo Images.
    """


    def __init__(self, driver_manager=None):
        self.driver_manager = driver_manager or LinboDriverManager()
        self.list()

    @staticmethod
    def _validated_driver_image(image):
        """Return an image basename supported by ``linbo_driverpostsync``."""

        if (
            not name_checker.check_linbo_image_name(image)
            or "." in image
            or len(image) > 100
        ):
            raise ValueError(
                "Driver image names must contain only [A-Za-z0-9_-] and be "
                "at most 100 characters long."
            )
        return image

    def _require_driver_image(self, image):
        image = self._validated_driver_image(image)
        if image not in self.groups:
            raise FileNotFoundError(f"LINBO image not found: {image}")
        return image

    @staticmethod
    def _atomic_replace(path, content, mode):
        """Atomically replace one small metadata or dispatcher file."""

        path = Path(path)
        descriptor, temporary = tempfile.mkstemp(
            prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
        )
        try:
            with os.fdopen(descriptor, "wb") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(temporary, mode)
            os.replace(temporary, path)
            directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
        except Exception:
            if os.path.exists(temporary):
                os.unlink(temporary)
            raise

    @classmethod
    def _restore_snapshot(cls, path, snapshot):
        if snapshot is None:
            try:
                Path(path).unlink()
            except FileNotFoundError:
                pass
            return
        content, mode = snapshot
        cls._atomic_replace(path, content, mode)

    @staticmethod
    def _write_image_conf(path, image):
        is_new = not os.path.lexists(path)
        with LMNFile(str(path), "w", convert_values=False) as image_file:
            data = image_file.read()
            data.clear()
            data.comments.clear()
            data.inline_comments.clear()
            data.initial_comment = []
            data.final_comment = []
            data["image"] = {"name": image}
            image_file.write(data)
        if is_new:
            Path(path).chmod(0o644)

    @staticmethod
    def _driverpostsync_path(image):
        return Path(LINBO_PATH) / image / f"{image}{DRIVERPOSTSYNC_SUFFIX}"

    def _inspect_driverpostsync(self, image):
        """Return the ownership state and snapshot of one dispatcher path."""

        path = self._driverpostsync_path(image)
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            return "missing", None
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            return "foreign", None
        if metadata.st_size > 1024 * 1024:
            return "foreign", None
        content = path.read_bytes()
        try:
            lines = content.decode("utf-8").splitlines()[:8]
        except UnicodeError:
            return "foreign", None
        if not DRIVERPOSTSYNC_OWNERSHIP_HEADERS.intersection(lines):
            return "foreign", None
        return "managed", (content, stat.S_IMODE(metadata.st_mode))

    def _snapshot_driverpostsync(self, image):
        """Snapshot a missing or unambiguously managed dispatcher."""

        state, snapshot = self._inspect_driverpostsync(image)
        if state == "foreign":
            path = self._driverpostsync_path(image)
            raise DriverPostsyncOwnershipError(
                f"Refusing to overwrite unmanaged driver postsync: {path}"
            )
        return snapshot

    def _read_profile_assignment(self, profile):
        """Read one already validated profile's direct image assignment."""

        path = Path(profile["path"]) / IMAGE_CONF_FILENAME
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            return None
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise ValueError(f"image.conf is not a regular file: {profile['name']}")

        try:
            with LMNFile(str(path), "r", convert_values=False) as image_file:
                data = image_file.read()
        except ConfigObjError as error:
            raise ValueError(
                f"Invalid image.conf for driver profile {profile['name']}: {error}"
            ) from error

        if set(data.keys()) != {"image"} or data.inline_comments.get("image"):
            raise ValueError(
                "image.conf must contain one canonical [image] section or "
                "one legacy image value."
            )

        section = data["image"]
        if isinstance(section, str):
            # Read compatibility for the standalone/.deb format. A subsequent
            # assignment rewrites it through LMNFile in canonical form.
            return self._validated_driver_image(section)

        if not isinstance(section, dict) or set(section.keys()) != {"name"}:
            raise ValueError("[image] must contain exactly one name.")
        if section.inline_comments.get("name"):
            raise ValueError("image.conf must not contain inline comments.")
        return self._validated_driver_image(section["name"])

    def get_driver_profile_image(self, profile_name):
        """Return a profile's canonical image assignment, if present."""

        profile = self.driver_manager.get_profile(profile_name)
        if profile is None:
            raise FileNotFoundError(f"Driver profile not found: {profile_name}")
        return self._read_profile_assignment(profile)

    def _assigned_driver_profiles(self, image):
        """Return all profiles referencing an image in deterministic order."""

        profiles = [
            profile["name"]
            for profile in self.driver_manager.list_profiles(strict=True)
            if self._read_profile_assignment(profile) == image
        ]
        return sorted(profiles, key=lambda value: (value.casefold(), value))

    @staticmethod
    def _render_driverpostsync(image, profiles):
        """Render the tiny dispatcher for the static LINBO runtime."""

        ordered = sorted(set(profiles), key=lambda value: (value.casefold(), value))
        profile_comment = ", ".join(ordered) or "(none)"
        arguments = "".join(f' "{profile}"' for profile in ordered)
        return (
            "#!/bin/sh\n"
            f"{DRIVERPOSTSYNC_MANAGED_HEADER}\n"
            f"# Image: {image}\n"
            f"# Profiles: {profile_comment}\n\n"
            "if ! command -v linbo_driverpostsync >/dev/null 2>&1; then\n"
            '    echo "linbo_driverpostsync is not available." >&2\n'
            "    return 1\n"
            "fi\n\n"
            f'linbo_driverpostsync "{image}"{arguments}\n'
            "return $?\n"
        )

    def _regenerate_driverpostsync(self, image):
        """Publish the desired dispatcher; the caller holds the mutation lock."""

        image = self._require_driver_image(image)
        profiles = self._assigned_driver_profiles(image)
        path = self._driverpostsync_path(image)
        self._snapshot_driverpostsync(image)
        content = self._render_driverpostsync(image, profiles).encode("utf-8")
        self._atomic_replace(path, content, 0o755)
        return {"image": image, "profiles": profiles, "path": str(path)}

    def reconcile_driverpostsyncs(self):
        """Repair managed dispatchers from the canonical ``image.conf`` files.

        Assigned images are always reconciled. Unassigned images are touched
        only when their existing dispatcher has an exact current or legacy
        ownership header. Unrelated files are reported but left unchanged.
        """

        self.driver_manager._ensure_base_directory()
        with _mutation_lock(self.driver_manager.base):
            assignments = {}
            for profile in self.driver_manager.list_profiles(strict=True):
                image = self._read_profile_assignment(profile)
                if image is not None:
                    assignments.setdefault(image, []).append(profile["name"])

            desired = {}
            snapshots = {}
            ignored = []
            for image in sorted(
                self.groups, key=lambda value: (value.casefold(), value)
            ):
                profiles = sorted(
                    assignments.pop(image, []),
                    key=lambda value: (value.casefold(), value),
                )
                state, snapshot = self._inspect_driverpostsync(image)
                if profiles:
                    if state == "foreign":
                        raise DriverPostsyncOwnershipError(
                            "Refusing to overwrite unmanaged driver postsync: "
                            f"{self._driverpostsync_path(image)}"
                        )
                elif state == "managed":
                    self._validated_driver_image(image)
                else:
                    if state == "foreign":
                        ignored.append(image)
                    continue

                desired[image] = self._render_driverpostsync(
                    image, profiles
                ).encode("utf-8")
                snapshots[image] = snapshot

            updated = []
            unchanged = []
            try:
                for image, content in desired.items():
                    snapshot = snapshots[image]
                    if (
                        snapshot is not None
                        and snapshot[0] == content
                        and snapshot[1] == 0o755
                    ):
                        unchanged.append(image)
                        continue
                    self._atomic_replace(
                        self._driverpostsync_path(image), content, 0o755
                    )
                    updated.append(image)
            except Exception as error:
                failures = []
                for image, snapshot in snapshots.items():
                    try:
                        self._restore_snapshot(
                            self._driverpostsync_path(image), snapshot
                        )
                    except Exception as rollback_error:
                        failures.append(rollback_error)
                if failures:
                    raise RuntimeError(
                        "Driver postsync reconciliation failed and could not "
                        "be rolled back completely."
                    ) from error
                raise

        return {
            "updated": updated,
            "unchanged": unchanged,
            "ignored": ignored,
            "missing": sorted(
                assignments, key=lambda value: (value.casefold(), value)
            ),
        }

    def _rollback_driver_assignment(self, image_conf, image_snapshot, hooks, cause):
        failures = []
        try:
            self._restore_snapshot(image_conf, image_snapshot)
        except Exception as error:
            failures.append(error)
        for image, snapshot in hooks.items():
            try:
                self._restore_snapshot(self._driverpostsync_path(image), snapshot)
            except Exception as error:
                failures.append(error)
        if failures:
            raise RuntimeError(
                "Driver assignment failed and could not be rolled back completely."
            ) from cause

    def assign_driver_profile(self, profile_name, image):
        """Assign one profile and regenerate every affected dispatcher."""

        self.driver_manager._ensure_base_directory()
        with _mutation_lock(self.driver_manager.base):
            profile = self.driver_manager.get_profile(profile_name)
            if profile is None:
                raise FileNotFoundError(
                    f"Driver profile not found: {profile_name}"
                )
            image = self._require_driver_image(image)
            previous = self._read_profile_assignment(profile)
            affected = sorted(
                {
                    name
                    for name in (previous, image)
                    if name == image or name in self.groups
                },
                key=lambda value: (value.casefold(), value),
            )

            image_conf = Path(profile["path"]) / IMAGE_CONF_FILENAME
            image_snapshot = None
            if previous is not None:
                metadata = image_conf.stat()
                image_snapshot = (
                    image_conf.read_bytes(),
                    stat.S_IMODE(metadata.st_mode),
                )
            hooks = {
                affected_image: self._snapshot_driverpostsync(affected_image)
                for affected_image in affected
            }
            try:
                self._write_image_conf(image_conf, image)
                for affected_image in affected:
                    self._regenerate_driverpostsync(affected_image)
            except Exception as error:
                self._rollback_driver_assignment(
                    image_conf, image_snapshot, hooks, error
                )
                raise
        return {"profile": profile["name"], "image": image}

    def unassign_driver_profile(self, profile_name):
        """Remove one assignment and leave a cleanup dispatcher behind."""

        self.driver_manager._ensure_base_directory()
        with _mutation_lock(self.driver_manager.base):
            profile = self.driver_manager.get_profile(profile_name)
            if profile is None:
                raise FileNotFoundError(
                    f"Driver profile not found: {profile_name}"
                )
            previous = self._read_profile_assignment(profile)
            if previous is None:
                return {"profile": profile["name"], "image": None}
            image_conf = Path(profile["path"]) / IMAGE_CONF_FILENAME
            metadata = image_conf.stat()
            image_snapshot = (
                image_conf.read_bytes(),
                stat.S_IMODE(metadata.st_mode),
            )
            hooks = {}
            if previous in self.groups:
                hooks[previous] = self._snapshot_driverpostsync(previous)
            try:
                image_conf.unlink()
                if previous in self.groups:
                    self._regenerate_driverpostsync(previous)
            except Exception as error:
                self._rollback_driver_assignment(
                    image_conf, image_snapshot, hooks, error
                )
                raise
        return {"profile": profile["name"], "image": None}

    def _delete_whole_image_group(self, group):
        """Delete an unassigned image group and its managed dispatcher."""

        self.driver_manager._ensure_base_directory()
        with _mutation_lock(self.driver_manager.base):
            profiles = self._assigned_driver_profiles(group)
            if profiles:
                raise DriverProfileAssignedError(profiles[0], group)
            hook = self._snapshot_driverpostsync(group)
            hook_path = self._driverpostsync_path(group)
            if hook is not None:
                hook_path.unlink()
            try:
                self.groups[group].delete()
            except Exception:
                if hook is not None and hook_path.parent.is_dir():
                    self._restore_snapshot(hook_path, hook)
                raise
        del self.groups[group]

    def list(self):
        """
        Browse LINBO_PATH to discover all linbo images.
        """

        self.groups = {}
        if not os.path.isdir(LINBO_PATH):
            return
        for dir in os.listdir(LINBO_PATH):
            if os.path.isdir(os.path.join(LINBO_PATH, dir)):
                for file in os.listdir(os.path.join(LINBO_PATH, dir)):
                    if file == f'{dir}.{IMAGE}':
                        self.groups[dir] = LinboImageGroup(dir)

    def delete(self, group, date=0, diff=False):
        """
        Delete a whole image and its backups. If date is given, only delete an
        associated backup. date and diff parameter excludes each other.

        :param group: Name of the linbo image
        :type group: str
        :param date: timestamp of a backup
        :type date: str
        :param diff: only delete a differential image
        :type diff: bool
        """

        if group in self.groups:
            # Apply assignment guards before the separate backup/diff paths.
            if not date and not diff:
                self._delete_whole_image_group(group)
                return
            if diff:
                # Only delete a differential image
                self.groups[group].diff_image.delete()
            elif date in self.images[group].backups:
                # The object to delete is only a backup
                self.groups[group].backups[date].delete()
                self.groups[group].load()
            else:
                self._delete_whole_image_group(group)

    def rename(self, group, new_name):
        """
        Rename a whole linbo image and its backups recursiverly.

        :param group: Name of the linbo image
        :type group: str
        :param new_name: New name for the linbo image
        :type new_name: str
        """

        if group in self.groups:
            self.driver_manager._ensure_base_directory()
            with _mutation_lock(self.driver_manager.base):
                profiles = self._assigned_driver_profiles(group)
                if profiles:
                    raise DriverProfileAssignedError(profiles[0], group)
                hook = self._snapshot_driverpostsync(group)
                old_hook_path = self._driverpostsync_path(group)
                staged_hook_path = None
                if hook is not None:
                    self._validated_driver_image(new_name)
                    staged_hook_path = Path(
                        self.groups[group].path,
                        f"{new_name}{DRIVERPOSTSYNC_SUFFIX}",
                    )
                    if os.path.lexists(staged_hook_path):
                        raise DriverPostsyncOwnershipError(
                            "Refusing to replace an existing staged driver "
                            f"postsync: {staged_hook_path}"
                        )
                    content = self._render_driverpostsync(
                        new_name, []
                    ).encode("utf-8")
                    self._atomic_replace(staged_hook_path, content, 0o755)
                try:
                    if hook is not None:
                        old_hook_path.unlink()
                    self.groups[group].rename(new_name)
                except Exception:
                    if old_hook_path.parent.is_dir():
                        if staged_hook_path is not None:
                            try:
                                staged_hook_path.unlink()
                            except FileNotFoundError:
                                pass
                        if hook is not None:
                            self._restore_snapshot(old_hook_path, hook)
                    raise
                self.groups[new_name] = LinboImageGroup(new_name)
                del self.groups[group]

    def duplicate(self, group, new_name):
        """
        Duplicate a whole linbo image without backups.

        :param group: Name of the linbo image to duplicate
        :type group: str
        :param new_name: New name for the linbo image
        :type new_name: str
        """

        if os.path.isdir(os.path.join(LINBO_PATH, new_name)):
            print(f"Directory {new_name} already exists")
            return

        if group in self.groups:
            shutil.copytree(
                os.path.join(LINBO_PATH, group),
                os.path.join(LINBO_PATH, new_name),
                ignore=_ignore_duplicate_files,
            )

            old_prefix = f'{group}.'
            new_prefix = f'{new_name}.'

            for file in os.listdir(os.path.join(LINBO_PATH, new_name)):
                if file.startswith(old_prefix):
                    os.rename(
                       os.path.join(LINBO_PATH, new_name, file),
                       os.path.join(LINBO_PATH, new_name, file.replace(old_prefix, new_prefix)),
                    )

            self.groups[new_name] = LinboImageGroup(new_name)
            self.groups[new_name].rename(new_name)

    def restore(self, group, date):
        """
        Delete a basic linbo image and restore a backup.

        :param group: Name of the linbo image
        :type group: str
        :param date: timestamp of a backup
        :type date: str
        """

        if group in self.groups:
            imageGroup = self.groups[group]
            if date in imageGroup.backups:
                timestamp = datetime.now().strftime(TIMESTAMP_FMT)
                new_backup_dir = os.path.join(
                    imageGroup.base.path,
                    'backups',
                    timestamp
                )

                if os.path.isdir(new_backup_dir):
                    print(f"Backup directory {new_backup_dir} already exists")
                    return
                
                os.mkdir(new_backup_dir)

                # Move base image to backup/timestamp
                for file in os.listdir(imageGroup.base.path):
                    # Avoid copying backups dir in itself
                    if file.endswith(DRIVERPOSTSYNC_SUFFIX):
                        continue
                    if os.path.isfile(os.path.join(imageGroup.base.path, file)):
                        shutil.move(os.path.join(imageGroup.base.path, file),
                                new_backup_dir)

                # Move backup to base image
                for file in os.listdir(imageGroup.backups[date].path):
                    if file.endswith(DRIVERPOSTSYNC_SUFFIX):
                        continue
                    shutil.move(os.path.join(imageGroup.backups[date].path, file),
                                imageGroup.base.path)

                # Cleanup and reload
                imageGroup.backups[date].delete()
                self.groups[group].load()

    def save_extras(self, group, data, timestamp=None, diff=False):
        """
        Save extra files for a base image, a backup or a differential
        image. timestamp and diff parameters excludes each other.

        :param group: Name of the linbo image
        :type group: str
        :param data: Content of the extra files
        :type data: dict
        :param timestamp: timestamp of a backup
        :type timestamp: str
        :param diff: data onlyc concern a diff image
        :type diff: bool
        """

        if timestamp:
            date = timestamp2date(timestamp)
        else:
            date = 0
        if group in self.groups:
            imageGroup = self.groups[group]
            if diff:
                imageGroup.diff_image.save_extras(data)
            elif date in imageGroup.backups:
                imageGroup.backups[date].save_extras(data)
            else:
                imageGroup.base.save_extras(data)

    def get_images_infos(self):
        """
        Export all necessary images informations for Linbo Docker project
        """


        images_list = []
        for name, image_group in self.groups.items():
            base_image = image_group.base

            files = [{
                "name": base_image.image,
                "size": base_image.info_file.imagesize,
                "type": "image"
            }]
            files_ext = []

            md5_content = None
            image_path = f"{base_image.path}/{base_image.image}"
            updated = os.stat(image_path).st_mtime

            for ext in ALL_FILES_EXT:
                if ext in EXTRA_COMMON_FILES:
                    ext_name = f"{name}.{ext}"
                else:
                    ext_name = f"{base_image.image}.{ext}"

                file_path = f"{LINBO_PATH}/{name}/{ext_name}"

                if os.path.isfile(file_path):
                    size = os.stat(file_path).st_size
                    files_ext.append(ext)
                    files.append({
                        "name": ext_name,
                        "size": size,
                        "type": "extra_file"
                    })

                    if ext == "md5":
                        with open(file_path, "r", encoding="utf-8") as f:
                            md5_content = f.read().strip().split()[0]

            images_list.append({
                "name": base_image.image,
                "filename": base_image.image,
                "base": name,
                "path": f"images/{name}/{base_image.image}",
                "size": base_image.info_file.imagesize,
                "md5": md5_content,
                "info": base_image.info_file.as_dict(),
                "description": base_image.extras['desc'],
                "extra_files": files_ext,
                "files": files,
                "updatedAt": datetime.fromtimestamp(updated, tz=timezone.utc).isoformat(),
            })

        return images_list
